version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: NPM Build
          command: npm run build
      - save_cache:
          key: git-sha-{{ .Revision }}
          paths:
            - node_modules
            - dist
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
          command: npm publish --tag develop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
